# -----------------------------------------------------------
# TBD

FROM geopython/pygeoapi:latest

LABEL maintainer="Tom Jones"

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

COPY ./pygeoapi-config.yml /pygeoapi/local.config.yml