
version: '3'

services:

  db:
#    image: postgis/postgis:latest
    build:
      context: ./
      dockerfile: Dockerfile-dev
    restart: always
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - LOGLEVEL=DEBUG
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
#    ports:
#      - "8877:8888"
#    volumes:
#      - ./:/opt/notebooks


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
      
#  pygeoapi:
#    image: geopython/pygeoapi:latest
#    volumes:
#      - ./my.config.yml:/pygeoapi/local.config.yml
